use sssp_rust::{Graph,random_sparse_graph,random_dense_graph,dijkstra,revision::{fast_sparse,paper_grid,finish}};
use std::{fs::{self,File},io::{BufRead,BufReader,BufWriter,Write},path::Path,collections::VecDeque};
fn hash(g:&Graph)->u64{let mut h=0xcbf29ce484222325u64;for(u,a)in g.adj.iter().enumerate(){for &(v,w)in a{for x in [u as u64,v as u64,w.to_bits()]{h=(h^x).wrapping_mul(0x100000001b3)}}}h}
fn expected(root:&Path,panel:&str,fam:&str,n:usize,seed:u64)->u64{let s=fs::read_to_string(root.join(format!("results/revision/{panel}/cases.csv"))).unwrap();for line in s.lines().skip(1){let p:Vec<_>=line.split(',').collect();if p[2]==fam&&p[3].parse::<usize>().unwrap()==n&&p[5].parse::<u64>().unwrap()==seed{return u64::from_str_radix(p[14],16).unwrap()}}panic!("missing saved graph")}
fn roads(path:&Path)->Graph{let mut g=Graph::new(0);let mut m=0;for line in BufReader::new(File::open(path).unwrap()).lines(){let line=line.unwrap();let p:Vec<_>=line.split_whitespace().collect();if p.is_empty(){continue}match p[0]{"p"=>{g=Graph::new(p[2].parse().unwrap());m=p[3].parse().unwrap()},"a"=>g.add_edge(p[1].parse::<usize>().unwrap()-1,p[2].parse::<usize>().unwrap()-1,p[3].parse().unwrap()),_=>{}}}assert_eq!(g.m,m);finish(&mut g);g}
fn export(g:&Graph,id:&str,seed:u64,source:usize,coords:Option<&Vec<(f64,f64)>>,out:&Path){
 let d=dijkstra(g,source);let mut ids=Vec::new();let mut selected=vec![false;g.n];let mut edges=Vec::new();let mut depth=vec![0usize;g.n];
 if coords.is_some(){let stride=(g.m/20000).max(1);let mut k=0;for(u,a)in g.adj.iter().enumerate(){for &(v,_)in a{if k%stride==0{edges.push((u,v));selected[u]=true;selected[v]=true}k+=1}}selected[source]=true;ids.extend((0..g.n).filter(|&v|selected[v]));}
 else if id=="grid"{ids.extend(0..g.n);selected.fill(true);for(u,a)in g.adj.iter().enumerate(){for &(v,_)in a{if u<v{edges.push((u,v))}}}}
 else {let limit=if id=="dense"{360}else{1400};let mut q=VecDeque::new();q.push_back(source);selected[source]=true;ids.push(source);while let Some(u)=q.pop_front(){if ids.len()>=limit{break}for &(v,_)in &g.adj[u]{if !selected[v]{selected[v]=true;depth[v]=depth[u]+1;ids.push(v);edges.push((u,v));q.push_back(v);if ids.len()>=limit{break}}}}for &u in &ids{for &(v,_)in &g.adj[u]{if selected[v]&&!edges.contains(&(u,v))&&edges.len()<5500{edges.push((u,v))}}}}
 let mut map=vec![usize::MAX;g.n];for(i,&v)in ids.iter().enumerate(){map[v]=i}let maxd=d.iter().copied().filter(|x|x.is_finite()).fold(0.0,f64::max).max(1.0);
 let key=format!("{id}-{seed}-{source}");let mut f=BufWriter::new(File::create(out.join(format!("{key}.nodes.csv"))).unwrap());writeln!(f,"id,x,y,distance,phase,source").unwrap();
 let maxdepth=ids.iter().map(|&v|depth[v]).max().unwrap_or(1).max(1)as f64;
 for &v in &ids{let(x,y)=if let Some(c)=coords{c[v]}else if id=="grid"{((v%100)as f64,(v/100)as f64)}else if v==source{(0.,0.)}else{let angle=((v as u64).wrapping_mul(2654435761)%1000003)as f64/1000003.*std::f64::consts::TAU;let r=(depth[v]as f64/maxdepth)*0.86+((v*17%113)as f64/113.)*0.13;(r*angle.cos(),r*angle.sin())};let phase=if d[v].is_finite(){((d[v]/maxd)*65534.).round()as u32}else{65535};writeln!(f,"{v},{x:.7},{y:.7},{},{phase},{}",if d[v].is_finite(){format!("{:.7}",d[v])}else{"inf".into()},v==source).unwrap();}
 let mut f=BufWriter::new(File::create(out.join(format!("{key}.edges.csv"))).unwrap());writeln!(f,"u,v").unwrap();for(u,v)in &edges{assert!(g.adj[*u].iter().any(|&(w,_)|w==*v));writeln!(f,"{},{}",map[*u],map[*v]).unwrap()}
 println!("{key}: full graph n={} m={}; display {} vertices, {} arcs; distances recomputed, not timed",g.n,g.m,ids.len(),edges.len());
}
fn main(){let args:Vec<_>=std::env::args().collect();let root=Path::new(&args[1]);let out=Path::new(&args[2]);fs::create_dir_all(out).unwrap();let mut log=BufWriter::new(File::create(out.join("fingerprints.csv")).unwrap());writeln!(log,"scenario,seed,fingerprint,n,m").unwrap();for id in ["sparse","million","dense","grid","ny","bay","col"]{let road=["ny","bay","col"].contains(&id);let seeds:Vec<u64>=if road{vec![0]}else{vec![42,1729,2026]};for seed in seeds{let(g,panel,fam)=match id{"sparse"=>(random_sparse_graph(10000,4,seed),"core","sparse"),"million"=>(fast_sparse(1000000,4,seed),"scale","sparse_fast"),"dense"=>(random_dense_graph(5000,0.1,seed),"core","dense"),"grid"=>(paper_grid(10000,seed),"core","grid"),_=>{let fam=match id{"ny"=>"NY","bay"=>"BAY",_=>"COL"};(roads(&root.join(format!("data/USA-road-d.{fam}.gr"))),"roads",fam)}};let fingerprint=hash(&g);assert_eq!(fingerprint,expected(root,panel,fam,g.n,seed),"graph fingerprint mismatch");writeln!(log,"{id},{seed},{fingerprint:016x},{},{}",g.n,g.m).unwrap();let mut coords=None;if road{let mut c=vec![(0.,0.);g.n];let mut seen=vec![false;g.n];for line in BufReader::new(File::open(out.join(format!("USA-road-d.{fam}.co"))).unwrap()).lines(){let line=line.unwrap();let p:Vec<_>=line.split_whitespace().collect();if p.first()==Some(&"v"){let v=p[1].parse::<usize>().unwrap()-1;assert!(!seen[v]);seen[v]=true;c[v]=(p[2].parse::<f64>().unwrap()/1e6,p[3].parse::<f64>().unwrap()/1e6)}}assert!(seen.iter().all(|&x|x));let lat=c.iter().map(|p|p.1).sum::<f64>()/g.n as f64;for p in &mut c{p.0*=lat.to_radians().cos();p.1= -p.1}coords=Some(c)}let sources:Vec<usize>=if road{(1..=6).map(|j|j*g.n/7).collect()}else{vec![g.n/3,2*g.n/3]};for s in sources{export(&g,id,seed,s,coords.as_ref(),out)}}}}
